
/* Drop Tables */

DROP TABLE AD_INFO CASCADE CONSTRAINTS;
DROP TABLE EVL CASCADE CONSTRAINTS;
DROP TABLE BBS_INFO CASCADE CONSTRAINTS;
DROP TABLE FLOWERROAD_INFO CASCADE CONSTRAINTS;
DROP TABLE MBER_INFO CASCADE CONSTRAINTS;




/* Create Tables */

-- 광고정보
CREATE TABLE AD_INFO
(
	-- 광고번호
	AD_NO varchar2(9) NOT NULL,
	-- 회원번호
	MBER_NO varchar2(9) NOT NULL,
	-- 광고주이름
	NM varchar2(30) NOT NULL,
	-- 광고주연락처
	TEL varchar2(11) NOT NULL,
	-- 광고주이메일
	EMAIL varchar2(50) NOT NULL,
	-- 광고제목
	AD_SJ varchar2(100) NOT NULL,
	-- 광고사진
	AD_Photh varchar2(100) NOT NULL,
	-- 광고설명
	AD_DC varchar2(1000),
	-- 시작일자
	BEGIN_DE varchar2(8) NOT NULL,
	-- 종료일자
	END_DE varchar2(8) NOT NULL,
	-- 광고비용
	AD_CT number(7,0) NOT NULL,
	-- 링크
	AD_LINK varchar2(100),
	-- 마감여부
	isCLOSE char NOT NULL,
	PRIMARY KEY (AD_NO)
);


-- 게시판정보
CREATE TABLE BBS_INFO
(
	-- 게시판구분
	BBS_SE varchar2(4) NOT NULL,
	-- 게시글번호
	BBSCTT_NO varchar2(9) NOT NULL,
	-- 회원번호
	MBER_NO varchar2(9) NOT NULL,
	-- 꽃길번호
	FLOWERROAD_NO varchar2(9),
	-- 게시글제목
	BBSCTT_SJ varchar2(100) NOT NULL,
	-- 작성자
	WRTER varchar2(30) NOT NULL,
	-- 작성일자
	WRITNG_DE varchar2(14) NOT NULL,
	-- 내용
	CN varchar2(3000) NOT NULL,
	-- 조회수
	RDCNT number(10) NOT NULL,
	-- 아이피주소
	IP varchar2(18) NOT NULL,
	-- REF
	BBS_REF number(4,0) NOT NULL,
	-- RE_STEP
	RE_STEP number(4,0) NOT NULL,
	-- RE_LEVEL
	RE_LEVEL number(4,0) NOT NULL,
	-- 삭제여부
	isDelete char DEFAULT 'N' NOT NULL,
	PRIMARY KEY (BBS_SE, BBSCTT_NO)
);


-- 평가
CREATE TABLE EVL
(
	-- 회원번호
	MBER_NO varchar2(9) NOT NULL,
	-- 게시판구분
	BBS_SE varchar2(4) NOT NULL,
	-- 게시글번호
	BBSCTT_NO varchar2(9) NOT NULL,
	-- 점수
	SCORE number(2,1) DEFAULT 0,
	-- 좋아요
	isLike char DEFAULT 'N',
	PRIMARY KEY (MBER_NO, BBS_SE, BBSCTT_NO)
);


-- 꽃길정보
CREATE TABLE FLOWERROAD_INFO
(
	-- 꽃길번호
	FLOWERROAD_NO varchar2(9) NOT NULL,
	-- 회원번호
	MBER_NO varchar2(9) NOT NULL,
	-- 꽃길구분
	FLOWERROAD_SE varchar2(4) NOT NULL,
	-- 꽃길명
	FLOWERROAD_NM varchar2(50) NOT NULL,
	-- 사업자 등록번호
	BSNM_CONFIRM_NO varchar2(10) NOT NULL UNIQUE,
	-- 시작시간
	BEGIN_TIME varchar2(4) NOT NULL,
	-- 종료시간
	END_TIME varchar2(4) NOT NULL,
	-- 꽃길주소
	FLOWERROAD_ADRES varchar2(200) NOT NULL,
	-- 연락처
	TEL varchar2(11) NOT NULL,
	-- Fax
	FAX varchar2(11),
	-- 이메일
	EMAIL varchar2(50),
	-- 기업사진
	ENTRPRS_PHOTO varchar2(100),
	-- 링크
	ENTRPRS_LINK varchar2(100),
	-- 진료동물
	CLNIC_ANIMAL varchar2(50),
	-- 기업소개
	ENTRPRS_INTRCN varchar2(1000) NOT NULL,
	-- 삭제여부
	isDelete char DEFAULT 'N' NOT NULL,
	PRIMARY KEY (FLOWERROAD_NO)
);


-- 회원정보
CREATE TABLE MBER_INFO
(
	-- 회원번호
	MBER_NO varchar2(9) NOT NULL,
	-- 회원구분
	MBER_SE varchar2(4) NOT NULL,
	-- 아이디
	ID varchar2(15) NOT NULL UNIQUE,
	-- 비밀번호
	PW varchar2(20) NOT NULL,
	-- 이름
	NM varchar2(30) NOT NULL,
	-- 닉네임
	NCNM varchar2(30) NOT NULL UNIQUE,
	-- 생년월일
	BRTHDY varchar2(8) NOT NULL,
	-- 주소
	ADRES varchar2(200),
	-- 연락처
	TEL varchar2(11),
	-- 이메일
	EMAIL varchar2(50),
	-- 관심동물
	INTRST_ANIMAL varchar2(50),
	-- 삭제여부
	isDelete char DEFAULT 'N' NOT NULL,
	PRIMARY KEY (MBER_NO)
);



/* Create Foreign Keys */

ALTER TABLE EVL
	ADD FOREIGN KEY (BBS_SE, BBSCTT_NO)
	REFERENCES BBS_INFO (BBS_SE, BBSCTT_NO)
;


ALTER TABLE BBS_INFO
	ADD FOREIGN KEY (FLOWERROAD_NO)
	REFERENCES FLOWERROAD_INFO (FLOWERROAD_NO)
;


ALTER TABLE AD_INFO
	ADD FOREIGN KEY (MBER_NO)
	REFERENCES MBER_INFO (MBER_NO)
;


ALTER TABLE BBS_INFO
	ADD FOREIGN KEY (MBER_NO)
	REFERENCES MBER_INFO (MBER_NO)
;


ALTER TABLE EVL
	ADD FOREIGN KEY (MBER_NO)
	REFERENCES MBER_INFO (MBER_NO)
;


ALTER TABLE FLOWERROAD_INFO
	ADD FOREIGN KEY (MBER_NO)
	REFERENCES MBER_INFO (MBER_NO)
;



/* Comments */

COMMENT ON TABLE AD_INFO IS '광고정보';
COMMENT ON COLUMN AD_INFO.AD_NO IS '광고번호';
COMMENT ON COLUMN AD_INFO.MBER_NO IS '회원번호';
COMMENT ON COLUMN AD_INFO.NM IS '광고주이름';
COMMENT ON COLUMN AD_INFO.TEL IS '광고주연락처';
COMMENT ON COLUMN AD_INFO.EMAIL IS '광고주이메일';
COMMENT ON COLUMN AD_INFO.AD_SJ IS '광고제목';
COMMENT ON COLUMN AD_INFO.AD_Photh IS '광고사진';
COMMENT ON COLUMN AD_INFO.AD_DC IS '광고설명';
COMMENT ON COLUMN AD_INFO.BEGIN_DE IS '시작일자';
COMMENT ON COLUMN AD_INFO.END_DE IS '종료일자';
COMMENT ON COLUMN AD_INFO.AD_CT IS '광고비용';
COMMENT ON COLUMN AD_INFO.AD_LINK IS '링크';
COMMENT ON COLUMN AD_INFO.isCLOSE IS '마감여부';
COMMENT ON TABLE BBS_INFO IS '게시판정보';
COMMENT ON COLUMN BBS_INFO.BBS_SE IS '게시판구분';
COMMENT ON COLUMN BBS_INFO.BBSCTT_NO IS '게시글번호';
COMMENT ON COLUMN BBS_INFO.MBER_NO IS '회원번호';
COMMENT ON COLUMN BBS_INFO.FLOWERROAD_NO IS '꽃길번호';
COMMENT ON COLUMN BBS_INFO.BBSCTT_SJ IS '게시글제목';
COMMENT ON COLUMN BBS_INFO.WRTER IS '작성자';
COMMENT ON COLUMN BBS_INFO.WRITNG_DE IS '작성일자';
COMMENT ON COLUMN BBS_INFO.CN IS '내용';
COMMENT ON COLUMN BBS_INFO.RDCNT IS '조회수';
COMMENT ON COLUMN BBS_INFO.IP IS '아이피주소';
COMMENT ON COLUMN BBS_INFO.BBS_REF IS 'REF';
COMMENT ON COLUMN BBS_INFO.RE_STEP IS 'RE_STEP';
COMMENT ON COLUMN BBS_INFO.RE_LEVEL IS 'RE_LEVEL';
COMMENT ON COLUMN BBS_INFO.isDelete IS '삭제여부';
COMMENT ON TABLE EVL IS '평가';
COMMENT ON COLUMN EVL.MBER_NO IS '회원번호';
COMMENT ON COLUMN EVL.BBS_SE IS '게시판구분';
COMMENT ON COLUMN EVL.BBSCTT_NO IS '게시글번호';
COMMENT ON COLUMN EVL.SCORE IS '점수';
COMMENT ON COLUMN EVL.isLike IS '좋아요';
COMMENT ON TABLE FLOWERROAD_INFO IS '꽃길정보';
COMMENT ON COLUMN FLOWERROAD_INFO.FLOWERROAD_NO IS '꽃길번호';
COMMENT ON COLUMN FLOWERROAD_INFO.MBER_NO IS '회원번호';
COMMENT ON COLUMN FLOWERROAD_INFO.FLOWERROAD_SE IS '꽃길구분';
COMMENT ON COLUMN FLOWERROAD_INFO.FLOWERROAD_NM IS '꽃길명';
COMMENT ON COLUMN FLOWERROAD_INFO.BSNM_CONFIRM_NO IS '사업자 등록번호';
COMMENT ON COLUMN FLOWERROAD_INFO.BEGIN_TIME IS '시작시간';
COMMENT ON COLUMN FLOWERROAD_INFO.END_TIME IS '종료시간';
COMMENT ON COLUMN FLOWERROAD_INFO.FLOWERROAD_ADRES IS '꽃길주소';
COMMENT ON COLUMN FLOWERROAD_INFO.TEL IS '연락처';
COMMENT ON COLUMN FLOWERROAD_INFO.FAX IS 'Fax';
COMMENT ON COLUMN FLOWERROAD_INFO.EMAIL IS '이메일';
COMMENT ON COLUMN FLOWERROAD_INFO.ENTRPRS_PHOTO IS '기업사진';
COMMENT ON COLUMN FLOWERROAD_INFO.ENTRPRS_LINK IS '링크';
COMMENT ON COLUMN FLOWERROAD_INFO.CLNIC_ANIMAL IS '진료동물';
COMMENT ON COLUMN FLOWERROAD_INFO.ENTRPRS_INTRCN IS '기업소개';
COMMENT ON COLUMN FLOWERROAD_INFO.isDelete IS '삭제여부';
COMMENT ON TABLE MBER_INFO IS '회원정보';
COMMENT ON COLUMN MBER_INFO.MBER_NO IS '회원번호';
COMMENT ON COLUMN MBER_INFO.MBER_SE IS '회원구분';
COMMENT ON COLUMN MBER_INFO.ID IS '아이디';
COMMENT ON COLUMN MBER_INFO.PW IS '비밀번호';
COMMENT ON COLUMN MBER_INFO.NM IS '이름';
COMMENT ON COLUMN MBER_INFO.NCNM IS '닉네임';
COMMENT ON COLUMN MBER_INFO.BRTHDY IS '생년월일';
COMMENT ON COLUMN MBER_INFO.ADRES IS '주소';
COMMENT ON COLUMN MBER_INFO.TEL IS '연락처';
COMMENT ON COLUMN MBER_INFO.EMAIL IS '이메일';
COMMENT ON COLUMN MBER_INFO.INTRST_ANIMAL IS '관심동물';
COMMENT ON COLUMN MBER_INFO.isDelete IS '삭제여부';



